### ISSUE TITLE
Class property function will not be patched

### ISSUE THREAD

**Issue by lix42** [gaearon/react-transform-hmr#26]
A simple example:

```
  render() {
    return (<div onClick={this.log} >{'foo'}</div>);
  }

  log = function() {
    console.log('foo');
  }
```

(property function needs Babel stage 0)

The change inside render function can HMR, however, the change inside log function will not HMR.

It seems react-transform-hmr only patch the function at **proto**, but not at the object instance.

For react on ES6+, class property function mainly used with arrow function to provide 'this' binding. See example at http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

So I suppose it's better to fix this bug.

For now, a work around way is not use class property function, but just use function bind at constructor.

I'll try to figure out a fix if I have time next week.

**Comment by gaearon** [comment]
This is kinda hard to implement because we can't hot reload something assigned in the constructor.
Any implementation of this would need to hoist actual methods into the class as hidden fields.

Finally, this proposal may not get implemented this way after all, so I wouldn't want to spend significant effort here until we know for sure.
https://github.com/gaearon/react-proxy/pull/8#issuecomment-142920524

Let's track this in https://github.com/gaearon/react-proxy/pull/8.

**Comment by gaearon** [comment]
(The approach I suggest is to use https://github.com/andreypopp/autobind-decorator instead.)
