### ISSUE TITLE
Hot reloading with react router dynamic routing

### ISSUE THREAD

**Issue by Justkant** [gaearon/react-transform-hmr#65]
Hi,

I'm building an app with the routing and architecture of [this](https://github.com/reactjs/react-router/tree/master/examples/auth-with-shared-root) react router example.
It appears to me that hot reloading is not able to bubble up because of the async function getComponent that react router [uses](https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md).
Can you confirm me that react router is the cause of the problem and not something else ?

Thx

**Comment by gaearon** [comment]
The most detailed info I can give about this is https://github.com/gaearon/react-transform-boilerplate#i-get-full-reload-needed-when-i-edit-some-files. If it doesn’t help, I don’t have any particular solution right now. Try asking in Webpack repo or investigating how HMR and bubbling works, and maybe you’ll figure out a solution yourself and share it with others.

In either case, I don’t think you want any bubbling behavior with `react-transform-hmr`. Its point is exactly to catch updates as early as possible (at component level) and prevent update bubbling. So it’s hard to say what the issue is without a **complete project reproducing it**.

**Comment by Justkant** [comment]
Thx for the reply.
I actually change the architecture to follow a simpler approach but I still have problem with hot reload.
I think that react-router-relay can be the cause of this. I will investigate and post here a solution if found.

**Comment by gaearon** [comment]
I really suggest you to first experiment with just React and hot reloading to better understand module update bubbling. For example try creating a new plain JS module and importing it from components vs from `index.js`. You’ll soon understand how bubbling works and in which cases HMR is successful. Then apply the same thinking to your problems (Relay, routing, etc).

**Comment by Justkant** [comment]
I already used the HMR on other projects with redux without any problem this is why is think relay and react-router-relay is in cause.
