### ISSUE TITLE
react-transform-hmr vs. webpack.HotModuleReplacementPlugin

### ISSUE THREAD

**Issue by ericmasiello** [gaearon/react-transform-hmr#81]
I know this project is dead and so I don't intend to use it. But just for my own edification, what was the difference between this and simply using webpack.HotModuleReplacementPlugin? Do the compliment one another in some way? Or is using both completely duplicative?

Thanks!

**Comment by AdilKhn** [comment]
As far as I understand it the webpack.HotModuleReplacement works for 'modules' in a webpack sense. Where as this project is geared for the react modules themselves.

@ericmasiello

**Comment by ericmasiello** [comment]
thanks @AdilKhn. So would webpack.HotModuleReplacementPlugin make react-transform-hmr unnecessary?

**Comment by AdilKhn** [comment]
No, it will need the react-hot-loader to handle the react components. The webpack.HotModuleReplacementPlugin allows updates in stuff like css files and other js stuff. But the react specific plugin is needed to keep react modules maintain their state. 
![image](https://user-images.githubusercontent.com/6991570/28640298-4212922c-7219-11e7-93e8-17f2fd0bf16c.png)


THis is a screenshot of what happens when i remove the react-transform-hmr. The previously hot updateable module wont update anymore. Once i plug in the new React-hot-loader then I should get that functionality back. Hope this makes sense.

**Comment by ericmasiello** [comment]
Ahhhhhhhh! Thanks that clarifies it :)
